// Case drill questions - broken down from full cases into bite-sized practice

import type { ChartData } from "@/components/ChartDisplay";
import { ALL_EXTRACTED_DRILLS } from "./drills_all";
import { CHART_DRILLS } from "./drills_charts";

export type DrillType = "choice" | "number" | "open";

export interface DrillQuestion {
  id: number;
  type: DrillType; // choice=选择题, number=填数字, open=开放式
  category: string;
  difficulty: "easy" | "medium" | "hard";
  source: string;
  question: string;
  // For choice type
  options?: string[];
  answer?: number; // index of correct option
  // For number type
  correctNumber?: number;
  tolerance?: number; // acceptable % range (e.g. 0.1 = ±10%)
  unit?: string;
  // For open type
  referenceAnswer?: string;
  keyPoints?: string[];
  // For chart type
  chartData?: ChartData;
  // Common
  explanation: string;
  timeLimit: number;
}

// 7 drill categories matching complete Case Interview flow:
// 听题→搭框架→看图表→做计算→估市场→头脑风暴→总结推荐
// McKinsey-inspired color scheme per category
export const DRILL_CATEGORIES = [
  { key: "structuring", label: "框架搭建", icon: "🏗️", color: "bg-[#051C2C]/5 text-[#051C2C] border-[#051C2C]/20" },
  { key: "calculation", label: "数学速算", icon: "🔢", color: "bg-[#E87722]/5 text-[#E87722] border-[#E87722]/20" },
  { key: "case_math", label: "商业计算", icon: "🧮", color: "bg-[#FFB81C]/10 text-[#9A6B00] border-[#FFB81C]/30" },
  { key: "sizing", label: "Market Sizing", icon: "📊", color: "bg-[#007680]/5 text-[#007680] border-[#007680]/20" },
  { key: "chart", label: "图表解读", icon: "📈", color: "bg-[#2251FF]/5 text-[#2251FF] border-[#2251FF]/20" },
  { key: "creativity", label: "头脑风暴", icon: "💡", color: "bg-[#00836E]/5 text-[#00836E] border-[#00836E]/20" },
  { key: "synthesis", label: "总结推荐", icon: "🎯", color: "bg-[#C4071B]/5 text-[#C4071B] border-[#C4071B]/20" },
];

export const DRILLS: DrillQuestion[] = [
  // All drills extracted from real casebooks
  ...ALL_EXTRACTED_DRILLS,
  ...CHART_DRILLS,
];

const _LEGACY: DrillQuestion[] = [
  {
    id: 1,
    type: "choice",
    category: "structuring",
    difficulty: "easy",
    source: "Airline Ancillary Revenue",
    question: "一家低成本航空公司想优化附加服务（行李、选座、WiFi）定价。你应该首先用什么框架切入？",
    options: [
      "波特五力分析",
      "定价三维度：成本、竞争、价值",
      "SWOT 分析",
      "BCG 矩阵",
    ],
    answer: 1,
    explanation: "定价问题的核心框架是三维度分析：Cost-Plus（成本加成）、Competitive Benchmarking（竞争对标）、Value-Based Pricing（价值定价）。波特五力和SWOT太宽泛，不够针对性。",
    timeLimit: 30,
  },
  {
    id: 2,
    type: "choice",
    category: "structuring",
    difficulty: "easy",
    source: "Airline Catering Co",
    question: "一家航空餐饮公司利润率从12%降到5%，收入稳定。最合适的分析框架是？",
    options: [
      "市场进入框架",
      "利润 = 收入 - 成本，重点拆成本端",
      "并购估值 DCF",
      "增长战略 Ansoff 矩阵",
    ],
    answer: 1,
    explanation: "收入稳定但利润下降 → 明显是成本端问题。用 Profit = Revenue - Cost 框架，收入端快速排除后，重点深挖成本端各项变化。",
    timeLimit: 25,
  },
  {
    id: 3,
    type: "choice",
    category: "structuring",
    difficulty: "medium",
    source: "Coffee Roaster",
    question: "一家精品咖啡烘焙商想从 B2B（供应餐厅）拓展到 DTC（直接面向消费者）。用什么框架？",
    options: [
      "利润下降分析框架",
      "市场进入框架：市场吸引力 + 自身能力 + 进入策略",
      "运营优化框架",
      "并购协同效应分析",
    ],
    answer: 1,
    explanation: "进入新渠道/新市场 → 经典的 Market Entry 框架。需要评估 DTC 市场规模、竞争格局、公司是否有品牌/渠道能力、以及具体进入方式（自建电商 vs 第三方平台）。",
    timeLimit: 30,
  },
  {
    id: 4,
    type: "choice",
    category: "structuring",
    difficulty: "medium",
    source: "EdTech Merger",
    question: "一家在线教育公司正在考虑收购一家小型 AI 教育创业公司。你会用什么框架分析？",
    options: [
      "定价策略框架",
      "市场规模估算",
      "并购框架：战略匹配 + 估值 + 协同效应 + 风险",
      "客户细分分析",
    ],
    answer: 2,
    explanation: "M&A 题标准框架：1) Strategic Fit（战略匹配度）2) Valuation（估值合理性）3) Synergies（协同效应）4) Risks（整合风险）。",
    timeLimit: 30,
  },
  {
    id: 5,
    type: "choice",
    category: "structuring",
    difficulty: "hard",
    source: "Gym Chain",
    question: "一家健身连锁品牌发现会员续费率从70%降到50%，同时新会员增长也放缓。应该怎么构建分析框架？",
    options: [
      "单一维度分析续费率下降原因",
      "分两条线：留存问题（为什么老会员流失）+ 获客问题（为什么新客减少），再找交叉根因",
      "直接做市场规模估算",
      "波特五力分析竞争格局",
    ],
    answer: 1,
    explanation: "两个问题可能有共同根因（比如竞争加剧、产品老化），也可能是独立问题。分两条线分析后寻找交叉点，是展示结构化思维的好机会。面试官会加分。",
    timeLimit: 35,
  },

  // === Math 数学速算 ===
  {
    id: 6,
    type: "choice",
    category: "case_math",
    difficulty: "easy",
    source: "Airline Catering Co",
    question: "航空餐饮公司年收入 $200M，利润率从 12% 降到 5%。利润减少了多少？",
    options: ["$10M", "$14M", "$24M", "$7M"],
    answer: 1,
    explanation: "原利润 = $200M × 12% = $24M，现利润 = $200M × 5% = $10M，减少 $14M。",
    timeLimit: 20,
  },
  {
    id: 7,
    type: "choice",
    category: "case_math",
    difficulty: "easy",
    source: "Burger Palace",
    question: "一家汉堡店日均卖 400 个汉堡，客单价 $8，月运营成本 $75,000。月利润是多少？（按30天算）",
    options: ["$21,000", "$16,000", "$96,000", "$25,000"],
    answer: 0,
    explanation: "月收入 = 400 × $8 × 30 = $96,000。月利润 = $96,000 - $75,000 = $21,000。",
    timeLimit: 25,
  },
  {
    id: 8,
    type: "choice",
    category: "case_math",
    difficulty: "medium",
    source: "SaaS Acquisition",
    question: "一家 SaaS 公司 ARR $50M，年增长 30%，客户流失率 10%。净新增 ARR 是多少？",
    options: ["$15M", "$10M", "$20M", "$5M"],
    answer: 1,
    explanation: "新增 ARR = $50M × 30% = $15M。流失 ARR = $50M × 10% = $5M。净新增 = $15M - $5M = $10M。",
    timeLimit: 30,
  },
  {
    id: 9,
    type: "choice",
    category: "case_math",
    difficulty: "medium",
    source: "Private Equity Retail",
    question: "PE 以 8x EBITDA 收购一家零售商（EBITDA $30M），持有5年后以 10x 退出，EBITDA 增长到 $45M。投资回报倍数是？",
    options: ["1.5x", "1.875x", "2.5x", "3x"],
    answer: 1,
    explanation: "买入价 = 8 × $30M = $240M。卖出价 = 10 × $45M = $450M。回报倍数 = $450M / $240M = 1.875x。",
    timeLimit: 35,
  },
  {
    id: 10,
    type: "choice",
    category: "case_math",
    difficulty: "hard",
    source: "Pharma Drug Pricing",
    question: "新药研发成本 $800M，专利期剩 10 年，目标患者群 200,000 人/年，渗透率预计 15%，需要多少年用药费才能收回研发成本？（假设年药价 $20,000/人）",
    options: ["约 1.3 年", "约 2.7 年", "约 4 年", "约 5.3 年"],
    answer: 1,
    explanation: "年患者数 = 200,000 × 15% = 30,000人。年收入 = 30,000 × $20,000 = $600M。无其他成本简化下，$800M / $600M ≈ 1.33年。但考虑实际运营和营销成本（通常占40-50%），净收入约 $300M/年，回收期 ≈ 2.7 年。",
    timeLimit: 45,
  },

  // === Judgment 商业判断 ===
  {
    id: 11,
    type: "choice",
    category: "creativity",
    difficulty: "easy",
    source: "Plant Based Meat",
    question: "植物肉品牌发现超市渠道销量停滞，但餐饮渠道增长 40%。以下哪个判断最合理？",
    options: [
      "应该放弃超市渠道",
      "消费者在餐厅更愿意尝试新品，超市购买更保守 → 应加强餐饮渠道同时优化超市策略",
      "植物肉市场已经饱和",
      "价格一定是唯一原因",
    ],
    answer: 1,
    explanation: "餐厅场景降低了尝试门槛（不用整包购买），且有厨师加工。超市停滞不代表要放弃，而是要调整策略（试吃、小包装、联名等）。",
    timeLimit: 30,
  },
  {
    id: 12,
    type: "choice",
    category: "creativity",
    difficulty: "medium",
    source: "Streaming Service",
    question: "一家流媒体平台用户增长 25%，但 ARPU（每用户收入）下降 15%。总收入是涨了还是跌了？",
    options: [
      "涨了，因为用户增长快于 ARPU 下降",
      "跌了，因为 ARPU 下降影响更大",
      "持平",
      "无法判断",
    ],
    answer: 0,
    explanation: "总收入 = 用户数 × ARPU。设原来100用户×$10 = $1000。现在125用户×$8.5 = $1062.5。涨了约 6.25%。快速心算：1.25 × 0.85 = 1.0625。",
    timeLimit: 30,
  },
  {
    id: 13,
    type: "choice",
    category: "creativity",
    difficulty: "medium",
    source: "Hotel Chain Luxury",
    question: "一家奢华酒店集团考虑推出中端子品牌。最大的风险是什么？",
    options: [
      "中端市场太小",
      "品牌稀释 — 中端子品牌可能损害主品牌的奢华定位",
      "运营成本太高",
      "员工不够",
    ],
    answer: 1,
    explanation: "奢侈品/高端品牌向下延伸的核心风险是品牌稀释（Brand Dilution）。万豪用不同品牌名（Courtyard vs Ritz-Carlton）就是为了避免这个问题。",
    timeLimit: 30,
  },
  {
    id: 14,
    type: "choice",
    category: "creativity",
    difficulty: "hard",
    source: "Renewable Energy",
    question: "一家传统能源公司投资新能源，短期利润会下降。以下哪个视角最能说服董事会？",
    options: [
      "环保是趋势，必须跟",
      "竞争对手都在投",
      "用 Real Options 思维：现在小额投资相当于买一个看涨期权，锁定未来大规模转型的能力，不投则失去选择权",
      "政府补贴可以覆盖成本",
    ],
    answer: 2,
    explanation: "Real Options 是说服 financial-minded 董事会的最强逻辑：不是赌博，是用小成本保留战略选择权。如果新能源爆发，我们有能力快速扩张；如果没有，损失有限。",
    timeLimit: 40,
  },

  // === Structure 结构化思维 ===
  {
    id: 15,
    type: "choice",
    category: "structuring",
    difficulty: "easy",
    source: "Call Center Efficiency",
    question: "客户要求分析呼叫中心效率低下的问题。以下哪个拆解最 MECE？",
    options: [
      "人员问题 / 系统问题 / 流程问题 / 管理问题",
      "输入（来电量和类型）→ 处理（人员×效率×工具）→ 输出（解决率和满意度）",
      "成本高 / 质量差",
      "内部原因 / 外部原因",
    ],
    answer: 1,
    explanation: "流程视角（输入→处理→输出）是分析运营效率的最佳 MECE 结构。选项A有重叠（管理影响人员和流程），选项C太粗，选项D不够具体。",
    timeLimit: 30,
  },
  {
    id: 16,
    type: "choice",
    category: "structuring",
    difficulty: "medium",
    source: "Food Delivery",
    question: "外卖平台想提高每单利润。以下哪个拆解方式最好？",
    options: [
      "收入高 vs 成本低",
      "每单利润 = 客单价×抽佣率 - 配送成本 - 补贴 - 分摊固定成本，逐项优化",
      "短期措施 vs 长期措施",
      "供给侧 vs 需求侧",
    ],
    answer: 1,
    explanation: "把 unit economics 拆成公式是最清晰的。每个变量都是一个优化杠杆：提高客单价、调整抽佣、优化配送路线降成本、减少补贴等。",
    timeLimit: 35,
  },

  // === Market Sizing ===
  {
    id: 17,
    type: "choice",
    category: "sizing",
    difficulty: "easy",
    source: "Pet Insurance",
    question: "估算中国宠物保险市场规模。以下哪个思路最合理？",
    options: [
      "中国人口 × 养宠率 × 买保险率 × 年保费",
      "保险公司数量 × 平均保费收入",
      "GDP × 保险渗透率",
      "宠物医院数量 × 平均转化率",
    ],
    answer: 0,
    explanation: "自上而下：14亿人 → 约3亿养宠家庭 → 宠物保险渗透率约1-2%（中国还很低）→ 300-600万份 × 年保费约1000-2000元 = 30-120亿元市场。",
    timeLimit: 30,
  },
  {
    id: 18,
    type: "choice",
    category: "sizing",
    difficulty: "medium",
    source: "EV Charging",
    question: "估算2025年中国需要多少个公共充电桩？最佳切入角度是？",
    options: [
      "从充电桩制造商产能估算",
      "从电动车保有量出发：车桩比 × 公共占比",
      "从电网负荷估算",
      "从停车场数量估算",
    ],
    answer: 1,
    explanation: "最直接：中国电动车保有量约2500万辆 → 目标车桩比约3:1 → 需约830万个充电桩 → 公共占比约30% → 约250万个公共充电桩。可以和实际数据对比验证。",
    timeLimit: 35,
  },

  // === Insight 数据洞察 ===
  {
    id: 19,
    type: "choice",
    category: "chart",
    difficulty: "easy",
    source: "Pharmacy Chain",
    question: "连锁药店数据：门店数增长 20%，总收入增长 10%，利润下降 5%。最关键的洞察是？",
    options: [
      "应该继续开店",
      "新店拉低了整体效率 — 同店收入在下降，且扩张成本侵蚀利润",
      "市场在萎缩",
      "药品降价是唯一原因",
    ],
    answer: 1,
    explanation: "门店+20% 但收入只+10% → 同店收入在下降（可能是新店选址不佳或市场饱和）。利润-5% → 扩张带来的固定成本增加超过了收入增长。核心问题是扩张效率。",
    timeLimit: 30,
  },
  {
    id: 20,
    type: "choice",
    category: "chart",
    difficulty: "hard",
    source: "Insurance Broker",
    question: "保险经纪公司数据：客户数+15%，保费总额+5%，佣金收入-3%。三个数据走势不一致，根因最可能是？",
    options: [
      "员工偷懒了",
      "获客渠道效果差",
      "新客户倾向买低保费产品（拉低均保费），且保险公司下调了佣金率",
      "市场萎缩",
    ],
    answer: 2,
    explanation: "客户+15%但保费只+5% → 单客保费在下降（新客户买小单）。保费+5%但佣金-3% → 佣金率被压缩。两个结构性问题叠加：客户结构恶化 + 佣金率下降。",
    timeLimit: 40,
  },

  // === Math Input 心算填空（填数字） ===
  {
    id: 21,
    type: "number",
    category: "calculation",
    difficulty: "easy",
    source: "Burger Palace",
    question: "一家汉堡店每天卖 600 个汉堡，客单价 $12。请计算日收入（单位：美元）。",
    correctNumber: 7200,
    tolerance: 0,
    unit: "$",
    explanation: "600 × $12 = $7,200。面试中快速算法：6 × 12 = 72，再加两个零。",
    timeLimit: 15,
  },
  {
    id: 22,
    type: "number",
    category: "calculation",
    difficulty: "easy",
    source: "Coffee Roaster",
    question: "咖啡店月收入 $180,000，食材成本占 35%，人工成本占 25%，租金 $30,000/月。月利润是多少？（单位：万美元）",
    correctNumber: 4.2,
    tolerance: 0.05,
    unit: "万$",
    explanation: "食材 = $180K × 35% = $63K。人工 = $180K × 25% = $45K。总成本 = $63K + $45K + $30K = $138K。利润 = $180K - $138K = $42K = 4.2万美元。",
    timeLimit: 30,
  },
  {
    id: 23,
    type: "number",
    category: "calculation",
    difficulty: "medium",
    source: "SaaS Acquisition",
    question: "SaaS 公司当前 MRR $2M，月增长率 5%。3 个月后的 MRR 是多少？（单位：百万美元，保留一位小数）",
    correctNumber: 2.3,
    tolerance: 0.05,
    unit: "M$",
    explanation: "$2M × 1.05³ = $2M × 1.1576 ≈ $2.3M。快速估算：5%增长3个月 ≈ 15%多一点（复利效应），$2M × 1.15 = $2.3M。",
    timeLimit: 30,
  },
  {
    id: 24,
    type: "number",
    category: "calculation",
    difficulty: "medium",
    source: "Airline Turnaround",
    question: "航空公司有 50 架飞机，每架每天飞 6 班。如果周转时间从 45 分钟减到 25 分钟，每架每天能多飞 1 班。每班平均收入 $35,000。年增收多少？（单位：亿美元，保留一位小数）",
    correctNumber: 6.4,
    tolerance: 0.1,
    unit: "亿$",
    explanation: "多飞班次 = 50架 × 1班/天 = 50班/天。日增收 = 50 × $35,000 = $1,750,000。年增收 = $1.75M × 365 ≈ $638.75M ≈ 6.4亿美元。",
    timeLimit: 40,
  },
  {
    id: 25,
    type: "number",
    category: "calculation",
    difficulty: "hard",
    source: "Private Equity Retail",
    question: "PE 基金以 $500M 收购零售商，用 60% 债务（利率 6%）+ 40% 股权。年 EBITDA $80M，维护性 CAPEX $15M，税率 25%。年股权自由现金流是多少？（单位：百万美元）",
    correctNumber: 26.25,
    tolerance: 0.1,
    unit: "M$",
    explanation: "债务 = $500M × 60% = $300M。年利息 = $300M × 6% = $18M。税前利润 = EBITDA - CAPEX - 利息 = $80M - $15M - $18M = $47M。税 = $47M × 25% = $11.75M。股权自由现金流 = $47M - $11.75M = $35.25M。（注：更精确的FCFE还需考虑还本，此处简化）实际约 $26-35M 范围都合理。",
    timeLimit: 60,
  },
  {
    id: 26,
    type: "number",
    category: "calculation",
    difficulty: "easy",
    source: "Pet Insurance",
    question: "宠物保险公司有 50,000 客户，年保费 $800/人，理赔率 45%，运营成本占保费 20%。年利润是多少？（单位：百万美元）",
    correctNumber: 14,
    tolerance: 0.05,
    unit: "M$",
    explanation: "保费总收入 = 50K × $800 = $40M。理赔 = $40M × 45% = $18M。运营 = $40M × 20% = $8M。利润 = $40M - $18M - $8M = $14M。",
    timeLimit: 30,
  },

  // === Structuring 框架搭建（开放式） ===
  {
    id: 27,
    type: "open",
    category: "structuring",
    difficulty: "easy",
    source: "Airline Catering Co",
    question: "一家航空餐饮公司利润率从 12% 降到 5%，收入稳定。请列出你的分析框架（至少 3 个一级分支）。",
    referenceAnswer: "利润 = 收入 - 成本\n\n一、收入端（快速排除）\n- 客户数 × 每客收入\n- 价格变化、合同结构\n\n二、成本端（重点深挖）\n- 原材料成本（食材价格波动）\n- 人工成本（工资、加班、人员配置）\n- 运营成本（物流、仓储、设备折旧）\n- 合规成本（食品安全、新法规）\n\n三、外部因素\n- 竞争格局变化\n- 客户谈判力（航司集中度）\n- 宏观因素（通胀、供应链）",
    keyPoints: ["收入端", "成本端", "原材料", "人工", "运营", "外部因素"],
    explanation: "这道题收入稳定已经给了提示，重点应该在成本端。好的框架需要 MECE（不重不漏）地拆解成本的各个组成部分，并考虑外部环境变化。",
    timeLimit: 120,
  },
  {
    id: 28,
    type: "open",
    category: "structuring",
    difficulty: "medium",
    source: "Coffee Chain Market Entry",
    question: "一家欧洲精品咖啡连锁想进入中国市场。请搭建你的分析框架。",
    referenceAnswer: "一、市场吸引力\n- 市场规模和增速（中国咖啡市场 CAGR ~15%）\n- 消费者行为和偏好（茶文化 vs 咖啡文化）\n- 竞争格局（星巴克、瑞幸、本地品牌）\n\n二、自身能力评估\n- 品牌认知度和差异化（欧洲精品定位）\n- 供应链能力（烘焙、物流）\n- 资金实力和管理经验\n\n三、进入策略\n- 进入方式：独资 vs 合资 vs 特许经营\n- 城市选择：一线先行 vs 二线突破\n- 本地化：菜单调整、数字化（小程序、外卖）\n\n四、财务评估\n- 投资规模和回报期\n- 单店经济模型\n- 风险因素和退出策略",
    keyPoints: ["市场规模", "竞争格局", "消费者", "品牌", "进入方式", "本地化", "财务"],
    explanation: "Market Entry 经典框架需要覆盖：市场（值不值得进）、能力（有没有能力进）、策略（怎么进）、财务（算不算得过来）。针对中国市场要特别关注本地化和数字化。",
    timeLimit: 150,
  },
  {
    id: 29,
    type: "open",
    category: "structuring",
    difficulty: "medium",
    source: "Gym Chain",
    question: "一家健身连锁品牌会员续费率从 70% 降到 50%，新会员增长也放缓。请搭建分析框架。",
    referenceAnswer: "一、留存问题（为什么老会员流失）\n- 产品/服务质量：设备老化、课程吸引力、教练质量\n- 价格因素：会费涨价、性价比降低\n- 竞争替代：新健身房、线上健身（Keep等）、私教工作室\n- 会员体验：拥挤度、卫生、便利性\n\n二、获客问题（为什么新客减少）\n- 市场容量：区域渗透率是否已饱和\n- 营销效果：获客渠道、转化率、获客成本变化\n- 品牌认知：口碑、社交媒体评价\n- 产品吸引力：对新客群（Z世代）的吸引力\n\n三、交叉分析\n- 是否有共同根因（如竞争加剧同时影响留存和获客）\n- 分门店/分区域对比，找到模式\n- 分会员类型分析（年卡 vs 月卡、不同年龄段）",
    keyPoints: ["留存", "流失原因", "获客", "竞争", "产品质量", "交叉分析"],
    explanation: "两个指标同时下降时，分两条线独立分析后寻找交叉根因，是面试中展示结构化思维的加分项。面试官会特别欣赏你主动做分门店/分客群的交叉分析。",
    timeLimit: 150,
  },
  {
    id: 30,
    type: "open",
    category: "structuring",
    difficulty: "hard",
    source: "EdTech Merger",
    question: "一家在线教育公司考虑以 $200M 收购一家 AI 教育创业公司。请搭建并购分析框架。",
    referenceAnswer: "一、战略匹配\n- 技术互补性：AI 能力是否填补自身短板\n- 产品协同：AI 功能能否嵌入现有产品线\n- 客户协同：用户群重叠度和交叉销售机会\n- 人才获取：核心 AI 团队的价值和留存风险\n\n二、估值合理性\n- 收入倍数 vs 同行可比公司\n- DCF：基于用户增长和变现能力预测\n- 替代方案成本：自建 vs 收购 vs 合作\n\n三、协同效应量化\n- 收入协同：交叉销售、新产品线、提价能力\n- 成本协同：技术共享、运营整合、去重\n- 协同时间表：6个月/1年/3年\n\n四、风险评估\n- 整合风险：文化冲突、关键人员流失\n- 技术风险：AI 技术能否规模化\n- 市场风险：AI 教育赛道竞争加剧\n- 监管风险：教育行业政策变化",
    keyPoints: ["战略匹配", "估值", "DCF", "协同效应", "收入协同", "成本协同", "整合风险", "人才"],
    explanation: "M&A 框架的四大支柱：Strategic Fit + Valuation + Synergies + Risks。高分答案需要在每个维度给出具体的分析角度，而不是泛泛而谈。特别注意「自建 vs 收购」的替代方案分析。",
    timeLimit: 180,
  },

  // === Chart Interpretation 图表解读 ===
  {
    id: 101,
    type: "choice",
    category: "chart",
    difficulty: "easy",
    source: "Coffee Chain Revenue",
    question: "根据下图，哪个区域的收入增长最快？",
    chartData: {
      type: "bar",
      title: "各区域年收入（$M）— 2024 vs 2025",
      categories: ["华东", "华南", "华北", "西南", "华中"],
      series: [
        { name: "2024", values: [120, 85, 95, 40, 55], color: "#93C5FD" },
        { name: "2025", values: [150, 110, 108, 68, 62], color: "#3B82F6" },
      ],
      unit: "M",
    },
    options: [
      "华东（+25%）",
      "华南（+29%）",
      "西南（+70%）",
      "华北（+14%）",
    ],
    answer: 2,
    explanation: "西南从$40M增到$68M，增长70%，远超其他区域。华东虽然绝对值最大增长$30M，但增长率只有25%。面试中注意区分绝对增长和相对增长率。",
    timeLimit: 30,
  },
  {
    id: 102,
    type: "choice",
    category: "chart",
    difficulty: "easy",
    source: "SaaS Metrics",
    question: "根据下图，该SaaS公司最应该担心什么？",
    chartData: {
      type: "line",
      title: "SaaS 公司关键指标趋势（按季度）",
      categories: ["Q1", "Q2", "Q3", "Q4"],
      series: [
        { name: "MRR ($K)", values: [200, 230, 255, 270], color: "#3B82F6" },
        { name: "客户数", values: [150, 168, 172, 170], color: "#10B981" },
        { name: "流失率%", values: [3, 4, 6, 9], color: "#EF4444" },
      ],
    },
    options: [
      "MRR增速放缓",
      "客户数见顶且流失率急剧上升",
      "客户数波动不定",
      "所有指标都在恶化",
    ],
    answer: 1,
    explanation: "最严重的信号是流失率从3%飙升到9%（3倍），加上客户数已在Q3-Q4停滞甚至下降。虽然MRR还在涨，但这可能是靠提价或升级掩盖了客户流失。这种模式如果不解决，MRR很快也会掉头向下。",
    timeLimit: 35,
  },
  {
    id: 103,
    type: "choice",
    category: "chart",
    difficulty: "medium",
    source: "Retail Market Share",
    question: "根据下图，以下哪个说法是正确的？",
    chartData: {
      type: "pie",
      title: "中国运动鞋市场份额（2025）",
      segments: [
        { label: "Nike", value: 25 },
        { label: "Adidas", value: 15 },
        { label: "安踏", value: 20 },
        { label: "李宁", value: 12 },
        { label: "特步", value: 8 },
        { label: "其他", value: 20 },
      ],
    },
    options: [
      "国际品牌占据超过一半市场",
      "国产品牌合计份额（40%）已超过Nike+Adidas（40%）",
      "安踏是市场份额最大的品牌",
      "长尾品牌（其他）的份额可忽略不计",
    ],
    answer: 1,
    explanation: "国产品牌（安踏20%+李宁12%+特步8%=40%）已与国际品牌（Nike 25%+Adidas 15%=40%）持平。Nike仍是单一最大品牌（25%>安踏20%），所以C错。国际品牌40%不算超过一半，A错。其他20%不可忽略，D错。",
    timeLimit: 35,
  },
  {
    id: 104,
    type: "choice",
    category: "chart",
    difficulty: "medium",
    source: "Airline Cost Structure",
    question: "根据瀑布图，如果该航空公司想改善利润率，最应该优先优化哪项成本？",
    chartData: {
      type: "waterfall",
      title: "航空公司单位座位成本分解（$/座位）",
      waterfall: [
        { label: "票价收入", value: 180, type: "increase" },
        { label: "燃油", value: -55, type: "decrease" },
        { label: "人工", value: -35, type: "decrease" },
        { label: "飞机租赁", value: -30, type: "decrease" },
        { label: "机场费", value: -20, type: "decrease" },
        { label: "维修", value: -15, type: "decrease" },
        { label: "其他", value: -10, type: "decrease" },
        { label: "利润", value: 15, type: "total" },
      ],
      unit: "$",
    },
    options: [
      "机场费 — 通过谈判降低",
      "燃油 — 占比最大的单项成本",
      "人工 — 减员增效",
      "飞机租赁 — 换更便宜的机型",
    ],
    answer: 1,
    explanation: "燃油是最大单项成本（$55，占总成本的33%）。航空业燃油对冲（fuel hedging）和机队燃油效率是利润率最大的杠杆。面试中关注最大项目而非最容易改的项目——先抓大头。",
    timeLimit: 30,
  },
  {
    id: 105,
    type: "choice",
    category: "chart",
    difficulty: "medium",
    source: "E-commerce GMV",
    question: "根据堆积柱状图，以下哪个趋势判断最准确？",
    chartData: {
      type: "stacked_bar",
      title: "电商平台各品类GMV（$B）",
      categories: ["2022", "2023", "2024", "2025E"],
      series: [
        { name: "服饰", values: [30, 32, 31, 29], color: "#EC4899" },
        { name: "电子", values: [25, 28, 33, 38], color: "#3B82F6" },
        { name: "生鲜", values: [8, 12, 18, 25], color: "#10B981" },
        { name: "家居", values: [15, 16, 17, 18], color: "#F59E0B" },
      ],
      unit: "B",
    },
    options: [
      "总GMV增长主要靠服饰品类驱动",
      "电子和生鲜是增长引擎，服饰正在萎缩",
      "所有品类都在持续增长",
      "家居是增速最快的品类",
    ],
    answer: 1,
    explanation: "电子从$25B增到$38B（+52%），生鲜从$8B增到$25B（+213%），都在快速增长。而服饰从$30B降到$29B，开始萎缩。家居增速缓慢（+20%）。总GMV增长的引擎是电子和生鲜，服饰和家居是拖后腿的。",
    timeLimit: 35,
  },
  {
    id: 106,
    type: "choice",
    category: "chart",
    difficulty: "hard",
    source: "Strategic Portfolio",
    question: "根据气泡图（气泡大小=利润额），CEO应该如何分配投资？",
    chartData: {
      type: "bubble",
      title: "业务组合分析（X=市场增速，Y=市场份额，气泡=利润）",
      xLabel: "市场增速 →",
      yLabel: "市场份额 →",
      bubbles: [
        { label: "A:传统业务", x: 2, y: 35, size: 80 },
        { label: "B:新兴SaaS", x: 25, y: 8, size: 15 },
        { label: "C:海外", x: 15, y: 12, size: 30 },
        { label: "D:IoT", x: 30, y: 3, size: 5 },
      ],
    },
    options: [
      "All-in传统业务A，因为利润最大",
      "砍掉A和C，全力投B和D（高增速市场）",
      "维持A现金流，重点投B和C，小额押注D",
      "平均分配到四个业务",
    ],
    answer: 2,
    explanation: "经典BCG矩阵思维：A是现金牛（高份额低增速），应维持但不追加重投；B和C是明星/问号（高增速），是增长引擎要重点投入；D增速最高但份额和利润太小，适合小额探索性投资。不应该平均撒胡椒面，也不应放弃现金牛。",
    timeLimit: 40,
  },
  {
    id: 107,
    type: "number",
    category: "chart",
    difficulty: "medium",
    source: "Revenue Mix Analysis",
    question: "根据下图，在线渠道的收入同比增长了多少百分比？（填整数）",
    chartData: {
      type: "stacked_bar",
      title: "某零售品牌渠道收入拆分（$M）",
      categories: ["2024", "2025"],
      series: [
        { name: "线下门店", values: [200, 180], color: "#F59E0B" },
        { name: "在线渠道", values: [80, 120], color: "#3B82F6" },
        { name: "批发", values: [50, 45], color: "#10B981" },
      ],
      unit: "M",
    },
    correctNumber: 50,
    tolerance: 0,
    unit: "%",
    explanation: "在线渠道从$80M增长到$120M，增长$40M，增长率 = 40/80 = 50%。同时注意线下门店从$200M降到$180M（-10%），说明渠道正在转移而非纯增长。",
    timeLimit: 25,
  },
  {
    id: 108,
    type: "choice",
    category: "chart",
    difficulty: "easy",
    source: "Customer Acquisition",
    question: "根据下图，该公司的获客成本（CAC）趋势说明什么？",
    chartData: {
      type: "line",
      title: "获客成本 vs 客户终身价值（$）",
      categories: ["Q1", "Q2", "Q3", "Q4", "Q1'", "Q2'"],
      series: [
        { name: "CAC", values: [50, 65, 80, 110, 140, 180], color: "#EF4444" },
        { name: "LTV", values: [200, 195, 190, 185, 180, 175], color: "#10B981" },
      ],
    },
    options: [
      "公司增长健康，CAC在合理范围内",
      "CAC即将超过LTV，商业模式面临不可持续风险",
      "LTV下降说明产品质量有问题",
      "应该停止获客，专注留存",
    ],
    answer: 1,
    explanation: "CAC从$50飙到$180（3.6倍），LTV从$200降到$175。Q2'时CAC=$180已接近LTV=$175，意味着每获一个新客户几乎不赚钱。如果趋势继续，很快CAC>LTV，每获客一个就亏一个。这是最危险的增长陷阱。",
    timeLimit: 30,
  },
  {
    id: 109,
    type: "choice",
    category: "chart",
    difficulty: "hard",
    source: "Profitability Analysis",
    question: "根据下图，哪个产品线应该被优先审查（可能砍掉或调整）？",
    chartData: {
      type: "horizontal_bar",
      title: "各产品线毛利率 vs 收入贡献",
      categories: ["产品A", "产品B", "产品C", "产品D", "产品E"],
      values: [45, 12, 28, -5, 35],
      unit: "%",
    },
    options: [
      "产品A — 虽然利润最高但可能市场饱和",
      "产品D — 唯一亏损的产品线，负毛利",
      "产品B — 毛利率最低的正利润产品",
      "产品E — 利润率中等，不够突出",
    ],
    answer: 1,
    explanation: "产品D是唯一负毛利（-5%）的产品线，每卖一单位就亏钱。应该优先审查：是新产品还在爬坡期？还是结构性亏损？能否提价或降本？如果都不行就应砍掉。面试中先找异常值（亏损/负数），再深挖原因。",
    timeLimit: 30,
  },
  {
    id: 110,
    type: "number",
    category: "chart",
    difficulty: "hard",
    source: "Market Dynamics",
    question: "根据下图，如果市场总量不变，安踏从2025到2026再增2个百分点份额，最可能从谁那里抢到？请估算Nike 2026年的份额。（填整数）",
    chartData: {
      type: "pie",
      title: "运动鞋市场份额变化（2024→2025）",
      segments: [
        { label: "Nike 28→25", value: 25 },
        { label: "Adidas 17→15", value: 15 },
        { label: "安踏 16→20", value: 20 },
        { label: "李宁 11→12", value: 12 },
        { label: "其他 28→28", value: 28 },
      ],
    },
    correctNumber: 23,
    tolerance: 0.05,
    unit: "%",
    explanation: "2024→2025的趋势显示：安踏+4pp，Nike-3pp，Adidas-2pp。安踏增长主要是从国际品牌那里抢份额。如果安踏再+2pp，大概率继续从Nike（-1~2pp）和Adidas（-0~1pp）抢。Nike估计从25%降到23%左右。",
    timeLimit: 40,
  },
  {
    id: 111,
    type: "choice",
    category: "chart",
    difficulty: "medium",
    source: "Subscription Business",
    question: "根据下图，该订阅业务最需要改善什么环节？",
    chartData: {
      type: "bar",
      title: "用户转化漏斗（月度，千人）",
      categories: ["访问", "注册", "试用", "付费", "续费"],
      values: [100, 35, 20, 8, 6],
      unit: "K",
    },
    options: [
      "访问→注册转化率太低（35%）",
      "注册→试用的转化（57%）还算健康",
      "试用→付费的转化率（40%）是最大瓶颈",
      "付费→续费（75%）说明产品粘性不错",
    ],
    answer: 0,
    explanation: "访问→注册只有35%，这是漏斗最大的流失点（65%的访客直接离开）。相比之下，注册→试用57%、试用→付费40%、付费→续费75%都相对健康。优化着陆页和注册流程的ROI最高——100K访客中如果注册率提到50%，后续每个环节都会等比例受益。",
    timeLimit: 35,
  },
  {
    id: 112,
    type: "choice",
    category: "chart",
    difficulty: "easy",
    source: "Regional Performance",
    question: "根据下图，经理应该关注哪个门店？",
    chartData: {
      type: "horizontal_bar",
      title: "各门店月度营收达标率（%）",
      categories: ["朝阳店", "海淀店", "浦东店", "南山店", "天河店"],
      values: [110, 95, 72, 105, 88],
      unit: "%",
    },
    options: [
      "朝阳店 — 超额完成需要总结经验",
      "浦东店 — 达标率最低，只有72%",
      "天河店 — 接近达标，稍加努力即可",
      "海淀店 — 略低于100%，问题不大",
    ],
    answer: 1,
    explanation: "浦东店只完成72%的目标，远低于其他门店。作为经理应该优先诊断浦东店：是目标设定过高？还是执行问题？竞争加剧？同时也应总结朝阳店（110%）的经验看能否复制。",
    timeLimit: 25,
  },
  {
    id: 113,
    type: "choice",
    category: "chart",
    difficulty: "hard",
    source: "Multi-variable Analysis",
    question: "根据下图，以下哪个业务判断最合理？",
    chartData: {
      type: "bubble",
      title: "客户细分分析（X=客单价，Y=复购率，气泡=客户数）",
      xLabel: "客单价 →",
      yLabel: "复购率 →",
      bubbles: [
        { label: "学生", x: 30, y: 60, size: 90 },
        { label: "白领", x: 80, y: 45, size: 50 },
        { label: "企业", x: 200, y: 80, size: 10 },
        { label: "退休", x: 50, y: 25, size: 30 },
      ],
    },
    options: [
      "学生群体是最有价值的客户——人数最多",
      "企业客户虽少但高客单价+高复购，LTV最高",
      "应该放弃退休群体和企业客户，专注学生和白领",
      "白领群体最均衡，应该是核心目标",
    ],
    answer: 1,
    explanation: "企业客户：客单价$200×复购率80%=LTV最高。虽然人数少（小气泡），但每个客户价值极高。学生虽人数多但客单价低。好的策略是：维持学生/白领的规模获客，同时重点提升企业客户数量（高LTV低量=增长空间大）。",
    timeLimit: 40,
  },
  {
    id: 114,
    type: "number",
    category: "chart",
    difficulty: "medium",
    source: "Cost Optimization",
    question: "根据瀑布图，如果团队将物流成本降低20%，新的利润率是多少？（原收入$500M不变，填百分比整数）",
    chartData: {
      type: "waterfall",
      title: "成本结构分解（$M）",
      waterfall: [
        { label: "收入", value: 500, type: "increase" },
        { label: "原材料", value: -180, type: "decrease" },
        { label: "人工", value: -100, type: "decrease" },
        { label: "物流", value: -80, type: "decrease" },
        { label: "营销", value: -60, type: "decrease" },
        { label: "其他", value: -40, type: "decrease" },
        { label: "利润", value: 40, type: "total" },
      ],
      unit: "M",
    },
    correctNumber: 11,
    tolerance: 0.1,
    unit: "%",
    explanation: "原利润 = $40M（利润率8%）。物流降20% = $80M × 20% = 节省$16M。新利润 = $40M + $16M = $56M。新利润率 = $56M / $500M = 11.2% ≈ 11%。物流优化让利润率从8%提升到11%，利润增加40%。",
    timeLimit: 35,
  },
  {
    id: 115,
    type: "choice",
    category: "chart",
    difficulty: "medium",
    source: "Trend Analysis",
    question: "根据下图趋势线，该公司Q1-2026最可能面临什么情况？",
    chartData: {
      type: "line",
      title: "季度经营数据",
      categories: ["Q1'25", "Q2'25", "Q3'25", "Q4'25"],
      series: [
        { name: "收入$M", values: [50, 52, 48, 45], color: "#3B82F6" },
        { name: "运营成本$M", values: [38, 40, 42, 44], color: "#EF4444" },
      ],
    },
    options: [
      "收入回升，利润改善",
      "收入和成本继续现有趋势，Q1-2026可能出现亏损",
      "成本会自然下降因为管理层在控制",
      "收入下降只是季节性波动",
    ],
    answer: 1,
    explanation: "收入趋势：50→52→48→45，Q3开始下降。成本趋势：38→40→42→44，持续上升。Q4利润已经只剩$1M（45-44）。如果两条线继续交叉，Q1-2026收入约$42-43M，成本约$45-46M，公司将进入亏损。这就是经典的「剪刀差」——必须立即行动。",
    timeLimit: 35,
  },

  // === Chart Interpretation 图表解读 — 开放式 ===
  {
    id: 120,
    type: "open",
    category: "chart",
    difficulty: "medium",
    source: "Retail Revenue Analysis",
    question: "请分析下图，列出你观察到的3个最重要的洞察，并说明对管理层的建议。",
    chartData: {
      type: "stacked_bar",
      title: "某零售品牌渠道收入拆分（$M）",
      categories: ["2022", "2023", "2024", "2025E"],
      series: [
        { name: "线下门店", values: [200, 190, 180, 160], color: "#FFB81C" },
        { name: "在线渠道", values: [40, 60, 90, 130], color: "#2251FF" },
        { name: "批发", values: [60, 55, 50, 40], color: "#007680" },
      ],
      unit: "M",
    },
    referenceAnswer: "洞察1：渠道结构剧变——线上从$40M增长到$130M（225%），线下从$200M降到$160M（-20%）。线上正在取代线下成为主渠道。\n\n洞察2：总收入基本持平（$300M→$330M），增长全靠线上驱动。如果线上增速放缓，公司将面临增长停滞。\n\n洞察3：批发渠道持续萎缩（$60M→$40M，-33%），可能反映了去中间化趋势或批发客户流失。\n\n建议：\n1. 加速DTC线上投入（小程序/自有APP），减少对第三方平台依赖\n2. 线下门店转型为体验店/展厅，不以销售额为唯一KPI\n3. 评估是否继续维持批发渠道，或将资源重新分配到线上",
    keyPoints: ["渠道转移", "线上增长", "线下下降", "批发萎缩", "总收入持平", "DTC"],
    explanation: "图表解读的开放题要求你不只是「看到什么」，还要说「so what」和「now what」。好的回答结构是：洞察→含义→建议。面试官看你能否从数据中提炼出actionable insight。",
    timeLimit: 120,
  },
  {
    id: 121,
    type: "open",
    category: "chart",
    difficulty: "hard",
    source: "SaaS Health Check",
    question: "你是一位SaaS公司的顾问。请分析下图，诊断这家公司最大的问题是什么，并给出你的优先行动建议。",
    chartData: {
      type: "line",
      title: "SaaS 公司关键指标（按季度）",
      categories: ["Q1", "Q2", "Q3", "Q4", "Q1'", "Q2'"],
      series: [
        { name: "MRR ($K)", values: [200, 220, 235, 245, 250, 248], color: "#2251FF" },
        { name: "新客MRR ($K)", values: [40, 45, 42, 35, 28, 22], color: "#00836E" },
        { name: "流失MRR ($K)", values: [15, 18, 22, 28, 30, 35], color: "#C4071B" },
      ],
    },
    referenceAnswer: "核心诊断：这家公司正在接近「增长天花板」——MRR从快速增长到几乎停滞（Q2' $248K vs Q1' $250K，首次下降）。\n\n根因分析：\n1. 新客获取能力急剧下降：新客MRR从$40K降到$22K（-45%），说明获客渠道在枯竭或CAC过高\n2. 流失在加速恶化：流失MRR从$15K升到$35K（+133%），老客户正在大量离开\n3. 交叉点即将到来：新客MRR（$22K）已接近流失MRR（$35K），如果趋势继续，下季度净MRR将为负——公司开始缩水\n\n优先行动：\n1. 【紧急】止血流失——立即启动高风险客户预警+客户成功团队介入，目标3个月内将流失率降回$20K以下\n2. 【短期】诊断获客下滑原因——是渠道饱和？竞对冲击？还是产品PMF偏移？\n3. 【中期】重新定义增长引擎——考虑向上销售(upsell)现有客户，而非纯靠新客驱动增长",
    keyPoints: ["MRR停滞", "新客下降", "流失加速", "交叉点", "止血", "客户成功", "upsell"],
    explanation: "高级图表解读不只是读数据，而是要：1)识别趋势和拐点；2)找到根因（不是表象）；3)预测如果不行动会怎样；4)给出有优先级的行动方案。注意新客MRR和流失MRR的交叉趋势是最关键的信号。",
    timeLimit: 150,
  },
  {
    id: 122,
    type: "open",
    category: "chart",
    difficulty: "medium",
    source: "Cost Optimization",
    question: "客户CEO问你：「我们的成本结构有什么问题？你建议从哪里开始优化？」请分析下图并回答。",
    chartData: {
      type: "waterfall",
      title: "成本结构（$M）— 收入到利润",
      waterfall: [
        { label: "收入", value: 400, type: "increase" },
        { label: "原材料", value: -120, type: "decrease" },
        { label: "人工", value: -90, type: "decrease" },
        { label: "物流", value: -70, type: "decrease" },
        { label: "营销", value: -55, type: "decrease" },
        { label: "研发", value: -30, type: "decrease" },
        { label: "管理", value: -25, type: "decrease" },
        { label: "利润", value: 10, type: "total" },
      ],
      unit: "M",
    },
    referenceAnswer: "成本结构分析：\n\n总成本$390M / 收入$400M = 利润率仅2.5%，极薄。\n\n按占收入比排序：\n1. 原材料 30%（$120M）— 最大单项\n2. 人工 22.5%（$90M）— 第二大\n3. 物流 17.5%（$70M）— 第三\n4. 营销 13.75%（$55M）\n5. 研发 7.5%（$30M）\n6. 管理 6.25%（$25M）\n\n优化建议（按影响从大到小）：\n\n1. 原材料（最大杠杆）：集中采购谈判、替代供应商评估、规格标准化减少SKU。如果降10%可省$12M，利润翻倍。\n2. 物流：路线优化、仓储整合、考虑3PL。如果降15%可省$10.5M。\n3. 营销：评估各渠道ROI，砍掉效率低的渠道。但要注意不能影响收入。\n\n不建议先动的：研发和管理——绝对值小，且砍研发会伤长期竞争力。",
    keyPoints: ["利润率薄", "原材料最大", "集中采购", "物流优化", "按影响排序", "不砍研发"],
    explanation: "瀑布图的读法：从左到右看每个成本项的「厚度」，厚的就是优化空间最大的。好的回答不只列数字，还要给出具体的优化手段和预期影响。注意提醒面试官：优化成本不等于全面砍成本——研发和关键人才是不能动的。",
    timeLimit: 150,
  },
  {
    id: 123,
    type: "open",
    category: "chart",
    difficulty: "easy",
    source: "Market Share Dynamics",
    question: "请分析下图，描述市场竞争格局的变化趋势，并预测未来1-2年可能的演变。",
    chartData: {
      type: "pie",
      title: "外卖平台市场份额（2025）",
      segments: [
        { label: "美团", value: 65 },
        { label: "饿了么", value: 25 },
        { label: "抖音外卖", value: 6 },
        { label: "其他", value: 4 },
      ],
    },
    referenceAnswer: "竞争格局分析：\n\n现状：美团以65%份额绝对领先，饿了么25%稳居第二，双寡头格局。但抖音外卖6%值得关注——这是一个快速增长的新进入者。\n\n关键趋势：\n1. 美团护城河深但增速放缓——65%份额意味着增长空间有限，未来更多靠提效而非扩份额\n2. 饿了么需要差异化——25%的份额不上不下，如果继续打价格战会被拖垮\n3. 抖音外卖是最大变量——背靠6亿DAU的流量入口，内容+外卖的模式可能改变游戏规则\n\n预测（未来1-2年）：\n- 美团：60-63%（微降，被抖音蚕食）\n- 饿了么：22-24%（微降或持平）\n- 抖音外卖：10-15%（翻倍增长最可能）\n- 催化剂：抖音是否全力投入补贴大战",
    keyPoints: ["双寡头", "美团主导", "抖音新进入", "流量优势", "份额预测"],
    explanation: "饼图分析不只是读数字，要看结构（集中度）、趋势（谁在涨谁在跌）、和未来（什么因素可能打破现有格局）。提到抖音的「流量+内容」模式是加分项。",
    timeLimit: 120,
  },
  {
    id: 124,
    type: "number",
    category: "chart",
    difficulty: "medium",
    source: "Growth Analysis",
    question: "根据下图，在线渠道2022到2025的年均复合增长率（CAGR）约是多少？（填百分比整数）",
    chartData: {
      type: "bar",
      title: "在线渠道收入（$M）",
      categories: ["2022", "2023", "2024", "2025"],
      values: [40, 60, 90, 130],
      unit: "M",
    },
    correctNumber: 48,
    tolerance: 0.1,
    unit: "%",
    explanation: "CAGR = (终值/初值)^(1/年数) - 1 = (130/40)^(1/3) - 1 = 3.25^0.333 - 1 ≈ 48%。3年从$40M增长到$130M，年均增长约48%。这是一个非常快的增长速度，说明线上渠道正在爆发。",
    timeLimit: 40,
  },

  // === Creativity 头脑风暴 ===
  {
    id: 201,
    type: "open",
    category: "creativity",
    difficulty: "easy",
    source: "Revenue Growth",
    question: "一家连锁咖啡品牌想在不开新店的情况下增加收入。请列举至少6种方法。",
    referenceAnswer: "1. 提高客单价：推出高端特调/联名款/季节限定\n2. 增加消费频次：会员积分/集章/订阅制（月卡）\n3. 拓展时段：增加早餐/下午茶/夜间酒饮\n4. 外卖/外带：上线美团/饿了么/小程序点单\n5. 零售产品：挂耳咖啡/咖啡豆/杯子周边\n6. 企业客户：团购/企业茶歇/包月服务\n7. 空间出租：下午时段出租给培训/会议\n8. 跨品类：卖轻食/甜点/面包\n9. 数字化：APP推送个性化优惠提高转化\n10. 涨价：测试不同价格弹性",
    keyPoints: ["客单价", "频次", "外卖", "零售", "会员", "企业"],
    explanation: "好的头脑风暴需要结构：按4P（产品/价格/渠道/促销）或者收入公式（客户数×频次×客单价）来发散。面试官看的是你能否有结构地快速产出多样化的想法。",
    timeLimit: 120,
  },
  {
    id: 202,
    type: "open",
    category: "creativity",
    difficulty: "easy",
    source: "Cost Reduction",
    question: "一家制造企业要在6个月内削减15%运营成本，但不能裁员。列举至少5种方法。",
    referenceAnswer: "1. 供应链优化：集中采购/谈判降价/替换供应商\n2. 能耗管理：LED照明/智能空调/错峰用电\n3. 流程自动化：RPA处理重复性工作/减少人工错误\n4. 库存优化：JIT管理/减少呆滞库存/降低仓储成本\n5. 外包非核心：清洁/安保/IT维护外包\n6. 减少浪费：精益生产/六西格玛/良品率提升\n7. 办公成本：减少出差（视频会议替代）/削减非必要订阅\n8. 设备维护：预防性维护减少停机/二手件替代\n9. 空间整合：关闭利用率低的仓库/办公区",
    keyPoints: ["供应链", "采购", "自动化", "库存", "外包", "能耗"],
    explanation: "成本削减的结构：固定成本 vs 可变成本，或按部门拆分（生产/供应链/行政/IT）。注意「不裁员」的约束——好的回答不是绕过限制，而是在限制内找创造性解法。",
    timeLimit: 120,
  },
  {
    id: 203,
    type: "open",
    category: "creativity",
    difficulty: "medium",
    source: "New Product Launch",
    question: "一家运动品牌想推出针对Z世代女性的新产品线。请从产品、定价、渠道、营销4个维度给出具体建议。",
    referenceAnswer: "产品：\n- 瑜伽裤/运动内衣为主打（高频刚需）\n- 强调可持续面料（Z世代环保意识强）\n- 提供定制化选项（颜色/印花）\n- 跨场景设计：运动→通勤→社交\n\n定价：\n- 中高端定位（$60-120），高于快时尚低于Lululemon\n- 首单折扣+推荐返现降低尝试门槛\n- 订阅制会员（月度新品优先购）\n\n渠道：\n- DTC为主（小程序+独立站）\n- 小红书/抖音种草→私域转化\n- 线下快闪店+健身房合作\n- KOC体验官计划\n\n营销：\n- 素人KOC > 明星代言（真实感）\n- UGC挑战赛（#穿着XX去运动）\n- 联名IP（泡泡玛特/迪士尼）\n- 社群运营（跑团/瑜伽群）",
    keyPoints: ["Z世代", "可持续", "DTC", "小红书", "KOC", "社群", "快闪"],
    explanation: "4P框架很适合产品策划的头脑风暴。面试中的加分项：1) 每个维度都有具体执行方案而非泛泛而谈；2) 方案之间有关联（如渠道策略支持营销策略）；3) 明确Why——为什么Z世代女性需要这些。",
    timeLimit: 150,
  },
  {
    id: 204,
    type: "open",
    category: "creativity",
    difficulty: "medium",
    source: "Strategy",
    question: "一家传统出租车公司面临网约车（滴滴/Uber）的冲击，收入下降30%。请给出3种不同的战略方向，并说明你推荐哪一种。",
    referenceAnswer: "方向一：拥抱平台\n- 加入滴滴/高德打车平台\n- 利用现有车队和司机资源\n- 优势：转型快，现有资产利用率高\n- 风险：利润率被平台挤压，沦为代工\n\n方向二：差异化服务\n- 聚焦高端/特定场景（机场接送/商务用车/包车旅游）\n- 打造品牌溢价（统一车型/培训司机/固定定价）\n- 优势：避开价格战，利润率高\n- 风险：市场规模小，增长有限\n\n方向三：转型平台\n- 自建小程序/APP，搞本地出行平台\n- 拉更多出租车公司入驻，做区域联盟\n- 优势：掌握流量，长期价值大\n- 风险：技术投入大，和巨头正面竞争\n\n推荐：方向一（短期）+ 方向二（中期）组合。先加入平台保住基本盘，同时逐步培养差异化能力。",
    keyPoints: ["平台", "差异化", "高端", "转型", "推荐", "组合"],
    explanation: "面试中给战略建议，最忌讳只给一条路。好的回答是：列出2-3条路径→分析各自优劣→给出推荐并解释why。推荐组合策略（短期+长期）通常比单一策略更成熟。",
    timeLimit: 150,
  },
  {
    id: 205,
    type: "open",
    category: "creativity",
    difficulty: "hard",
    source: "Innovation",
    question: "一家大型银行想吸引年轻客户（18-30岁），目前年轻客户占比只有8%。请列举至少8个具体可执行的举措。",
    referenceAnswer: "产品创新：\n1. 全数字化开户（5分钟手机开户，无需线下）\n2. 零门槛理财产品（1元起投，游戏化收益展示）\n3. 虚拟信用卡+消费分期（低门槛+灵活还款）\n4. 储蓄挑战功能（52周存钱/round-up零钱存款）\n\n体验升级：\n5. APP重新设计（社交化UI，类似支付宝/Venmo）\n6. 即时转账+AA分账（朋友间转账体验优化）\n7. 消费分析dashboard（自动分类+月度账单报告）\n\n获客渠道：\n8. 校园大使计划（学生KOL推广返佣）\n9. 和奶茶/咖啡品牌联名卡（消费返现）\n10. 入驻支付宝/微信小程序（去到年轻人在的地方）\n\n品牌营销：\n11. 年轻化IP联名（泡泡玛特联名卡面）\n12. B站/小红书内容营销（理财科普而非硬广）",
    keyPoints: ["数字化", "理财", "APP", "校园", "联名", "社交", "小程序", "游戏化"],
    explanation: "8个以上具体举措需要你从多个角度发散：产品/体验/渠道/品牌/定价。面试官评估的是：1)数量是否足够多样；2)是否真的可执行而非空话；3)是否理解年轻人的真实需求（便捷>利率，社交>功能）。",
    timeLimit: 150,
  },
  {
    id: 206,
    type: "open",
    category: "creativity",
    difficulty: "easy",
    source: "Customer Retention",
    question: "一家健身房会员续费率从70%降到50%。请列举至少5个可能的原因。",
    referenceAnswer: "外部因素：\n1. 竞争加剧：新竞对开业（超级猩猩/乐刻），分流会员\n2. 替代品兴起：居家健身（Keep/Switch/YouTube）疫情后习惯保留\n3. 经济下行：消费降级，健身被列为非必要支出\n\n内部因素：\n4. 服务质量下降：教练流失/器材老化/卫生问题\n5. 体验差：高峰期太挤/课程不更新/APP不好用\n6. 定价问题：续费价格涨了但价值感没提升\n7. 销售骚扰：过度推销私教/附加课程引发反感\n8. 位置问题：搬家/换工作后距离变远\n\n数据维度：\n9. 新会员vs老会员续费率分别是多少？（新人留存通常更低）\n10. 哪类会员流失最多？（按频次/年龄/会员类型拆分）",
    keyPoints: ["竞争", "替代", "服务", "价格", "体验", "教练"],
    explanation: "诊断类问题用内因+外因结构。先列外部不可控因素（竞争/替代/宏观），再列内部可控因素（服务/价格/体验）。加分项是主动提出「需要数据验证」的分析维度。",
    timeLimit: 90,
  },
  {
    id: 207,
    type: "open",
    category: "creativity",
    difficulty: "medium",
    source: "Digital Transformation",
    question: "一家传统连锁超市想提高线上销售占比（目前只有5%），目标是2年内达到25%。列举你的完整行动方案。",
    referenceAnswer: "阶段一（0-6个月）：基础设施\n- 搭建小程序商城+接入美团/饿了么\n- 门店改造：增加前置仓/拣货区\n- 配送体系：自配+第三方骑手并行\n\n阶段二（6-12个月）：用户获取\n- 线下引流线上：收银台扫码领券/门店WiFi弹窗\n- 新人首单补贴（免配送费+折扣）\n- 社区团购：小区团长模式\n- 会员体系打通：线上线下积分互通\n\n阶段三（12-24个月）：提升粘性\n- 订阅制：每周菜篮子/水果箱定期配送\n- 个性化推荐：基于购买历史推荐商品\n- 直播带货：门店店长直播+限时闪购\n- 到店自提优惠（降低配送成本）\n\n关键指标追踪：\n- 线上GMV占比（5%→25%）\n- 线上订单成本 vs 线下\n- 线上用户复购率\n- 客单价对比",
    keyPoints: ["小程序", "前置仓", "社区团购", "补贴", "订阅", "会员", "直播", "指标"],
    explanation: "面试中给数字化转型方案，关键是分阶段推进（不能一口气全做），每个阶段有重点，最后加上衡量指标。面试官看的是你的计划是否可执行、有优先级、有量化目标。",
    timeLimit: 150,
  },
  {
    id: 208,
    type: "open",
    category: "creativity",
    difficulty: "hard",
    source: "Market Entry",
    question: "一家中国新能源车企（类似蔚来）想进入东南亚市场。请给出进入策略的完整框架。",
    referenceAnswer: "一、市场选择（Where）\n- 优先泰国：最大汽车市场+政府EV补贴+日系主导但中国品牌已破冰\n- 次选印尼：人口最多+镍矿资源（电池原料）\n- 暂缓越南：VinFast本土强势\n\n二、进入方式（How）\n- 初期：出口+本地经销商（轻资产试水）\n- 中期：CKD组装厂（关税优势+本地化）\n- 长期：全产业链本地化（电池厂+充电网络）\n\n三、产品策略（What）\n- 不打旗舰，先推$15-25K中端SUV（东南亚主流价格带）\n- 右舵版本适配（泰国/印尼右舵）\n- 强调性价比：比日系更多科技配置+更低使用成本\n\n四、本地化关键\n- 充电基础设施：和电力公司/物业合作建桩\n- 售后网络：和现有4S店集团合作\n- 品牌认知：赞助本地赛事/KOL试驾\n- 政府关系：申请EV生产补贴/免关税\n\n五、风险\n- 日系品牌反击（降价/推EV）\n- 基础设施不足（充电焦虑）\n- 汇率风险（泰铢/印尼盾波动）\n- 地缘政治风险",
    keyPoints: ["泰国", "印尼", "经销商", "CKD", "充电", "本地化", "右舵", "补贴"],
    explanation: "Market Entry的完整框架：Where（市场选择）→ How（进入方式）→ What（产品策略）→ 本地化 → 风险。面试中给出这个结构本身就是加分项，内容需要具体到国家/价格/合作方式。",
    timeLimit: 180,
  },
  {
    id: 209,
    type: "open",
    category: "creativity",
    difficulty: "medium",
    source: "Turnaround",
    question: "一家曾经很火的网红餐厅品牌（类似文和友），现在同店收入连续3个季度下降。请给出诊断框架和至少6个可能的原因。",
    referenceAnswer: "诊断框架：\n按收入公式拆分：收入 = 客流量 × 客单价 × 翻台率\n\n客流量下降原因：\n1. 网红效应消退：打卡拍照的新鲜感过了\n2. 竞争分流：新网红餐厅/新商业综合体开业\n3. 口碑下滑：大众点评评分下降/社交媒体差评\n4. 位置老化：所在商圈客流整体下降\n\n客单价/翻台率下降：\n5. 菜品不更新：长期不换菜单，回头客减少\n6. 服务质量下降：扩张太快，标准化执行不到位\n7. 性价比感知差：价格涨了但体验没提升\n\n结构性问题：\n8. 过度依赖周末/节假日：工作日空置率高\n9. 外卖冲击：消费者从堂食转向外卖\n10. 品牌定位模糊：文化体验店还是餐饮店？不上不下",
    keyPoints: ["客流", "翻台率", "网红效应", "竞争", "菜品", "口碑", "服务"],
    explanation: "诊断收入下降的经典思路：先拆公式（流量×转化×客单价），再从外部和内部分别找原因。网红餐厅的特殊性在于它本质上是一种「体验消费」，新鲜感消退是最大的结构性风险。",
    timeLimit: 120,
  },
  {
    id: 210,
    type: "open",
    category: "creativity",
    difficulty: "hard",
    source: "Pricing Strategy",
    question: "一家B2B SaaS公司现在按用户数收费（$20/user/月），CEO想改成按使用量收费。请分析利弊，并给出你的建议。",
    referenceAnswer: "按使用量收费的优势：\n1. 降低客户准入门槛：小客户可以低成本试用\n2. 更公平的价值匹配：用得多付得多，客户感知更合理\n3. 自动扩展收入：随客户业务增长，收入自然增长\n4. 减少shelfware（买了不用）：每个用户都是真实活跃的\n\n风险/劣势：\n1. 收入不可预测：客户用量波动→MRR不稳定\n2. 客户预算不确定：CFO不喜欢每月账单不一样\n3. 使用量定义复杂：API调用？存储？计算？指标难选\n4. 大客户可能付更少：高频用户可能要求量大折扣\n5. 迁移风险：现有客户续约时可能反弹\n\n建议：\n混合模式 — 基础费（$X/月保底）+ 超出部分按量计费\n- 保底费覆盖固定成本，给公司收入可预测性\n- 按量部分给客户灵活性和公平感\n- 设计3个tier（Starter/Growth/Enterprise），每个tier包含不同的基础用量\n- 迁移策略：老客户12个月内按原价保护，新客户直接新定价",
    keyPoints: ["门槛", "可预测", "公平", "混合模式", "保底", "迁移", "tier"],
    explanation: "定价策略变更题，面试官要看到你不是简单地说好或坏，而是：1)系统性列出利弊；2)给出具体方案（通常是混合/折中）；3)考虑了迁移策略（老客户怎么办）。",
    timeLimit: 150,
  },
  // === Synthesis 总结推荐 ===
  {
    id: 301,
    type: "open",
    category: "synthesis",
    difficulty: "medium",
    source: "Coffee Chain Profitability",
    question: "你为一家连锁咖啡品牌做利润诊断，发现以下3个关键发现：\n1. 原材料成本过去2年涨了25%（咖啡豆+牛奶）\n2. 外卖订单占比从15%升到40%，但外卖平台抽佣25%\n3. 新开的30家门店中有12家还未盈亏平衡\n\n请给CEO一个30秒的结构化推荐。",
    referenceAnswer: "CEO，基于我们的分析，利润下降主要由三个因素驱动，我建议分短期和中期两步走：\n\n短期（立即执行）：\n1. 原材料：锁定6个月期货合约对冲价格波动，同时评估替代供应商（预计节省8-10%采购成本）\n2. 外卖：将外卖价格上调10-15%覆盖平台佣金，同时推自有小程序点单（目标6个月内自有渠道占外卖30%）\n\n中期（3-6个月）：\n3. 新店：对12家亏损门店逐一诊断——给6个月观察期，达不到盈亏平衡的考虑关店或转为卫星厨房（只做外卖）\n\n预期影响：这三项措施合计预计可恢复利润率3-5个百分点。\n\n下一步：需要进一步分析各门店的单位经济模型和客户画像数据来验证。",
    keyPoints: ["短期", "中期", "原材料", "外卖", "门店", "量化", "下一步"],
    explanation: "Synthesis的核心是：结论先行→分优先级（短期/中期）→每条建议有具体动作和量化预期→最后说下一步。面试官看的是你能否把零散发现串成一个有逻辑的故事，而不是重复念发现。",
    timeLimit: 120,
  },
  {
    id: 302,
    type: "open",
    category: "synthesis",
    difficulty: "easy",
    source: "Retail Market Entry",
    question: "你的客户（一家中国服装品牌）在考虑进入东南亚市场。分析发现：\n1. 泰国和印尼市场规模最大（各$5B+）\n2. 客户在中国的核心优势是性价比和快速上新\n3. 当地已有Shein和本土品牌竞争激烈\n\n请用金字塔结构给出你的推荐。",
    referenceAnswer: "结论：建议进入，优先选择泰国，采用线上DTC模式试水。\n\n理由一：市场有吸引力\n- 泰国+印尼合计$10B+市场，且仍在增长\n- 东南亚消费者对中国品牌接受度逐年提升（TikTok Shop带动）\n\n理由二：客户有竞争优势\n- 快速上新能力（2周vs行业4-6周）在东南亚时尚市场是核心壁垒\n- 性价比定位匹配东南亚主流消费力\n\n理由三：进入策略可控风险\n- 先通过Shopee/Lazada/TikTok Shop线上试水（零线下成本）\n- 选泰国优先（物流基础设施好于印尼，市场更集中）\n- 6个月验证PMF后再考虑线下\n\n风险提示：\n- Shein在东南亚已有强势地位，需要差异化（非纯低价）\n- 物流时效和退货率需要本地仓支持\n\n下一步：做一个3个月的线上试点，投入预算$200-500K，KPI是月GMV达到$50K和复购率15%+。",
    keyPoints: ["结论先行", "泰国", "DTC", "快速上新", "风险", "下一步", "KPI"],
    explanation: "金字塔结构的Synthesis：先给结论（进不进+怎么进），再给3个支撑理由，最后说风险和下一步。注意每个理由都要有具体的数据或事实支撑。",
    timeLimit: 120,
  },
  {
    id: 303,
    type: "open",
    category: "synthesis",
    difficulty: "hard",
    source: "SaaS Turnaround",
    question: "你为一家SaaS公司做了全面诊断，核心发现：\n1. MRR增长放缓（YoY从80%降到20%）\n2. 流失率从3%升到8%（主要是中小客户）\n3. 企业客户（>$50K ARR）流失率只有1%，但销售周期长达9个月\n4. 产品NPS从45降到28\n5. 竞争对手推出了AI功能，定价低30%\n\n请给董事会一个2分钟的结构化汇报。",
    referenceAnswer: "各位董事，我们的核心判断是：公司面临的不是增长问题，而是产品竞争力问题。增长放缓和流失率上升都是表象，根因是产品NPS下降和竞对AI功能冲击。\n\n我们建议三步走：\n\n第一步（立即，0-3个月）：止血\n- 对流失风险最高的中小客户做主动关怀（客户成功团队1对多）\n- 推出年付折扣锁定现有客户（减少月度流失窗口）\n- 预计可将流失率从8%降到5%\n\n第二步（3-6个月）：产品反击\n- All-in AI功能开发，至少追平竞对\n- 把AI作为高级tier的核心卖点（不是免费给，是创造升级动力）\n- 预计6个月内NPS回升到35+\n\n第三步（6-12个月）：客户结构调整\n- 逐步将资源从中小客户转向企业客户\n- 企业客户流失率1%、LTV是中小客户的20倍\n- 虽然销售周期长，但每签一个企业客户=200个中小客户的价值\n- 目标：12个月内企业客户ARR占比从30%提到50%\n\n财务影响：\n- 保守估计，这三步可在12个月内将MRR增速恢复到40%+\n- 需要额外投入：AI研发$2M + 企业销售团队扩招$1M\n\n最大风险：AI功能研发延迟或效果不及预期。缓解措施是考虑收购一家小型AI公司加速。\n\n下一步：我们需要董事会批准$3M追加预算，以及批准客户结构调整的战略方向。",
    keyPoints: ["根因", "止血", "AI", "企业客户", "客户结构", "财务影响", "预算", "风险", "下一步"],
    explanation: "董事会级别的Synthesis需要：1)一句话核心判断（不是问题罗列）；2)分阶段行动计划（紧急/中期/长期）；3)每步有量化预期；4)总体财务影响；5)最大风险+缓解；6)明确的ask（需要董事会做什么决定）。",
    timeLimit: 180,
  },
  {
    id: 304,
    type: "choice",
    category: "synthesis",
    difficulty: "easy",
    source: "Recommendation Structure",
    question: "你完成了一个盈利能力诊断，准备给CEO做最终推荐。以下哪种开场方式最有效？",
    options: [
      "让我按照分析顺序，从市场分析讲到成本分析，再到竞争分析...",
      "我们的核心建议是聚焦高毛利产品线并退出亏损业务，预计可提升利润率5个百分点。让我解释为什么。",
      "这个项目我们做了很多分析，有几个有趣的发现想和您分享...",
      "根据波特五力和SWOT分析框架，我们得出以下结论...",
    ],
    answer: 1,
    explanation: "Synthesis必须结论先行（Conclusion First）。选项B直接给出核心建议+量化影响，然后才展开理由。A按分析顺序讲是最常见的错误——CEO没耐心听你的过程。C太随意，D太学术。记住：先说What（建议）和So What（影响），再说Why（理由）。",
    timeLimit: 25,
  },
  {
    id: 305,
    type: "choice",
    category: "synthesis",
    difficulty: "medium",
    source: "Recommendation Prioritization",
    question: "你有4条建议要给客户，但只有30秒时间。以下哪种排序方式最好？\n\nA: 按分析发现的顺序\nB: 按实施难度从易到难\nC: 按影响力从大到小\nD: 按短期到长期时间线",
    options: [
      "A — 保持分析的逻辑连贯性",
      "B — 先说容易做的让客户有信心",
      "C — 先说影响最大的抓住注意力",
      "D — 先说能立即执行的",
    ],
    answer: 2,
    explanation: "推荐排序的首要原则是Impact First——先说影响最大的建议。CEO最关心的是「哪个动作杠杆最大」，而不是你的分析顺序或实施难度。如果时间被打断，至少最重要的建议已经传达。D（时间线排序）是可以的但不如C，因为短期动作不一定是最重要的。",
    timeLimit: 30,
  },
  {
    id: 306,
    type: "open",
    category: "synthesis",
    difficulty: "medium",
    source: "Gym Chain",
    question: "健身房连锁品牌分析发现：\n1. 会员续费率从70%降到50%\n2. 新会员获取成本从$50升到$120\n3. 高峰时段（18:00-21:00）使用率95%，其他时段只有30%\n4. 私教课程利润率60%，但只有15%会员购买\n\n请给出elevator pitch（30秒推荐）。",
    referenceAnswer: "核心问题是留存，不是获客。续费率暴跌20个百分点才是最大的利润杀手。\n\n我建议三件事：\n\n第一，提升非高峰使用率：推出「早鸟卡」和「午间卡」（折扣30%），把30%的空闲容量变现，同时缓解高峰拥挤（拥挤是续费率下降的可能原因之一）\n\n第二，私教渗透率翻倍：从15%提到30%——私教会员的续费率通常比普通会员高2倍。推出「首次体验课免费」+3节体验包$99，降低尝试门槛\n\n第三，暂停扩张获客支出：CAC从$50翻到$120说明获客效率在恶化，先把钱花在留住现有会员上，ROI更高\n\n预期影响：续费率回升到60%+私教渗透翻倍，预计6个月内利润改善15-20%。",
    keyPoints: ["留存", "续费率", "非高峰", "私教", "暂停获客", "量化"],
    explanation: "Elevator pitch要在30秒内传达：1)核心判断（问题是什么）；2)最多3条建议（不是5条）；3)每条有一个数字支撑；4)预期影响。语言要简洁有力，避免铺垫。",
    timeLimit: 90,
  },
  {
    id: 307,
    type: "choice",
    category: "synthesis",
    difficulty: "hard",
    source: "Risk Communication",
    question: "你的推荐方案有一个重大风险：竞争对手可能在6个月内推出类似产品。面试官问「你怎么处理这个风险？」以下哪种回答最好？",
    options: [
      "这个风险很小，我们不用太担心",
      "我们应该放弃这个方案，选择风险更小的替代方案",
      "我承认这个风险存在。缓解方案是：加速上市时间从12个月压到8个月，同时申请关键技术专利构建壁垒。即使竞对跟进，我们有4个月先发优势积累用户",
      "我们需要做更多调研才能评估这个风险的大小",
    ],
    answer: 2,
    explanation: "处理风险的正确姿势：1)承认风险存在（不回避）；2)给出具体缓解措施（不是泛泛说「我们会注意」）；3)解释即使风险发生，为什么方案仍然可行。A回避风险会失分，B过度保守，D推迟决策。面试官想看到你在不确定性下仍能做判断。",
    timeLimit: 30,
  },
  {
    id: 308,
    type: "open",
    category: "synthesis",
    difficulty: "hard",
    source: "M&A Recommendation",
    question: "客户（一家医疗器械公司）在考虑以$500M收购一家AI诊断创业公司。你的分析发现：\n1. 目标公司技术领先但尚未盈利（年亏损$20M）\n2. 协同效应预计$80M/年（收入协同$50M+成本协同$30M）\n3. 估值按DCF是$350-400M，$500M有20-30%溢价\n4. 主要风险：核心团队（12人AI团队）可能在收购后离职\n\n请给出你的最终推荐（Recommend / Not Recommend + 理由 + 条件）。",
    referenceAnswer: "推荐：有条件地推荐收购。\n\n核心理由：\n1. 战略价值大于财务溢价：AI诊断是医疗器械的必然趋势，自建至少需要3-5年和$100M+投入。$500M收购虽有溢价，但时间价值和确定性远超自建。\n2. 协同效应覆盖溢价：$80M/年协同效应意味着2年内即可覆盖$100-150M的溢价。即使协同效应打5折（$40M/年），4年也能覆盖。\n\n关键条件（必须写入交易结构）：\n1. 核心团队锁定：12人AI团队签3年竞业+留任奖金（建议$30-50M留任池，分3年发放）\n2. 对赌条款：$500M中$100M与技术里程碑挂钩（如FDA认证、产品上线）\n3. 整合计划：保持目标公司独立运营6-12个月，避免文化冲突导致人才流失\n\n风险缓解：\n- 最大风险（团队流失）已通过留任池+竞业条款锁定\n- 估值风险通过对赌条款部分转移\n\n下一步：启动尽职调查，重点关注IP归属和核心人员合同条款。",
    keyPoints: ["有条件推荐", "战略价值", "协同效应", "团队锁定", "对赌", "独立运营", "风险缓解", "下一步"],
    explanation: "M&A推荐不应该是简单的Yes/No，而是「有条件推荐」——说清楚在什么条件下推荐。核心框架：1)战略理由；2)财务可行性；3)关键交易条件；4)风险缓解；5)下一步。溢价分析要说清楚「溢价多少可以接受，为什么」。",
    timeLimit: 180,
  },
  // (legacy hand-written drills below — no longer used)
];

// ========== Auto-generated Math Drills ==========
// Generates random math problems on the fly

interface MathTemplate {
  generate: () => DrillQuestion;
}

const MATH_TEMPLATES: MathTemplate[] = [
  // Revenue calculation
  {
    generate: () => {
      const units = Math.round((Math.random() * 900 + 100) / 50) * 50;
      const price = Math.round((Math.random() * 90 + 10) / 5) * 5;
      const days = 30;
      const answer = units * price * days;
      return {
        id: 10000 + Math.floor(Math.random() * 90000),
        type: "number",
        category: "calculation",
        difficulty: "easy",
        source: "自动生成",
        question: `一家店铺日均销量 ${units} 件，单价 $${price}。月收入是多少？（按${days}天算，单位：美元）`,
        correctNumber: answer,
        tolerance: 0,
        unit: "$",
        explanation: `${units} × $${price} × ${days} = $${answer.toLocaleString()}`,
        timeLimit: 20,
      };
    },
  },
  // Profit margin
  {
    generate: () => {
      const revenue = Math.round((Math.random() * 400 + 100) / 10) * 10;
      const marginOld = Math.round(Math.random() * 10 + 8);
      const marginNew = Math.round(Math.random() * 5 + 2);
      const diff = revenue * (marginOld - marginNew) / 100;
      return {
        id: 10000 + Math.floor(Math.random() * 90000),
        type: "number",
        category: "calculation",
        difficulty: "easy",
        source: "自动生成",
        question: `公司年收入 $${revenue}M，利润率从 ${marginOld}% 降到 ${marginNew}%。利润减少了多少？（单位：百万美元）`,
        correctNumber: diff,
        tolerance: 0.05,
        unit: "M$",
        explanation: `原利润 = $${revenue}M × ${marginOld}% = $${(revenue * marginOld / 100).toFixed(1)}M。现利润 = $${revenue}M × ${marginNew}% = $${(revenue * marginNew / 100).toFixed(1)}M。减少 $${diff.toFixed(1)}M。`,
        timeLimit: 20,
      };
    },
  },
  // Breakeven
  {
    generate: () => {
      const fixedCost = Math.round((Math.random() * 400 + 100) / 50) * 50;
      const price = Math.round((Math.random() * 40 + 10) / 5) * 5;
      const varCost = Math.round(price * (Math.random() * 0.3 + 0.3) / 5) * 5;
      const breakeven = Math.round(fixedCost * 1000 / (price - varCost));
      return {
        id: 10000 + Math.floor(Math.random() * 90000),
        type: "number",
        category: "calculation",
        difficulty: "medium",
        source: "自动生成",
        question: `新店固定成本 $${fixedCost}K/月，产品售价 $${price}，单位可变成本 $${varCost}。每月需要卖多少件才能盈亏平衡？`,
        correctNumber: breakeven,
        tolerance: 0.05,
        unit: "件",
        explanation: `单位贡献利润 = $${price} - $${varCost} = $${price - varCost}。盈亏平衡 = $${fixedCost},000 ÷ $${price - varCost} = ${breakeven.toLocaleString()} 件。`,
        timeLimit: 30,
      };
    },
  },
  // Growth rate
  {
    generate: () => {
      const base = Math.round((Math.random() * 80 + 20) / 5) * 5;
      const rate = Math.round(Math.random() * 20 + 5);
      const years = Math.floor(Math.random() * 3) + 2;
      const result = Math.round(base * Math.pow(1 + rate / 100, years) * 10) / 10;
      return {
        id: 10000 + Math.floor(Math.random() * 90000),
        type: "number",
        category: "calculation",
        difficulty: "medium",
        source: "自动生成",
        question: `公司当前收入 $${base}M，年增长率 ${rate}%。${years} 年后收入约是多少？（单位：百万美元，保留一位小数）`,
        correctNumber: result,
        tolerance: 0.1,
        unit: "M$",
        explanation: `$${base}M × (1+${rate}%)^${years} = $${base}M × ${Math.pow(1 + rate / 100, years).toFixed(3)} ≈ $${result}M`,
        timeLimit: 35,
      };
    },
  },
  // Market share
  {
    generate: () => {
      const totalMarket = Math.round((Math.random() * 900 + 100) / 50) * 50;
      const share = Math.round(Math.random() * 20 + 5);
      const result = Math.round(totalMarket * share / 100 * 10) / 10;
      return {
        id: 10000 + Math.floor(Math.random() * 90000),
        type: "number",
        category: "calculation",
        difficulty: "easy",
        source: "自动生成",
        question: `某行业市场总规模 $${totalMarket}B，你的客户占 ${share}% 市场份额。客户收入约是多少？（单位：十亿美元，保留一位小数）`,
        correctNumber: result,
        tolerance: 0.05,
        unit: "B$",
        explanation: `$${totalMarket}B × ${share}% = $${result}B`,
        timeLimit: 15,
      };
    },
  },
];

export function generateMathDrill(): DrillQuestion {
  const template = MATH_TEMPLATES[Math.floor(Math.random() * MATH_TEMPLATES.length)];
  return template.generate();
}

export function generateMathDrills(count: number): DrillQuestion[] {
  return Array.from({ length: count }, () => generateMathDrill());
}

// Shuffle helper
export function shuffleDrills(drills: DrillQuestion[]): DrillQuestion[] {
  const arr = [...drills];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
